use std::error::Error; // Import the Error trait

fn main() -> Result<(), Box<dyn Error>> {
    println!("This is a test program.");
    Ok(())
}